### ISSUE TITLE
Duplicate Present Sticker (Gold)

### ISSUE THREAD

**Issue by achatman** [kappanjoe/seedling-tracker#1]
Present Sticker (Gold) is showing up twice under Special:
![Duplicate Present Sticker Gold](https://user-images.githubusercontent.com/26806401/236980503-f04dffb3-9922-4837-b689-50cbaee444aa.png)

**Comment by kappanjoe** [comment]
Fixed by commit [b1eec91](https://github.com/kappanjoe/seedling-tracker/commit/b1eec9188203b6da75c019d531d6f2f19e46be50)
